## Introduction to PyTorch
### What is a Tensor? 
A tensor, in the context of PyTorch, is a multi-dimensional array used to represent data. It's similar to arrays in Python or ndarrays in NumPy, but with additional features that make it suitable for deep learning applications.

### Installation of PyTorch
Before we start coding, you need to install PyTorch. Assuming that you have Python installed, you can install PyTorch by running the following command in your terminal:

In [2]:
# !pip install torch torchvision

This command installs not only PyTorch (torch), but also torchvision (torchvision), which provides datasets and model architectures for computer vision.

### Getting Started with Tensors
To start with PyTorch, we need to import it,

In [3]:
import torch

c:\Users\AB012DH\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\AB012DH\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\AB012DH\Anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


You can create a tensor with a specific data type using torch.tensor(). Here is an example:

In [4]:
t1 = torch.tensor([1, 2, 3])
print(t1)

tensor([1, 2, 3])


In this code, we've created a 1-dimensional tensor. You can also create a 2-dimensional tensor like this:

In [5]:
t2 = torch.tensor([[1, 2], [3, 4]])
print(t2)

tensor([[1, 2],
        [3, 4]])


You can check the shape of a tensor (i.e., its dimensions) using the .shape attribute:

In [6]:
print(t2.shape)

torch.Size([2, 2])


This tells you that t2 is a 2x2 tensor (a matrix with 2 rows and 2 columns).

#### Mathematical Operations
Now let's dive into some mathematical operations that we can perform on tensors.

Addition:

You can add two tensors of the same shape:

In [7]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = t1 + t2

print(t3)

tensor([5, 7, 9])


Multiplication:

You can also multiply two tensors:

In [8]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = t1 * t2

print(t3)

tensor([ 4, 10, 18])


Note that this is element-wise multiplication, not matrix multiplication.

Matrix Multiplication:

For matrix multiplication, you can use torch.matmul():

In [18]:
t1 = torch.tensor([[1, 2], [4, 3]])
t2 = torch.tensor([[3, 4], [2, 1]])
t3 = torch.matmul(t1, t2)

print(t3)

tensor([[ 7,  6],
        [18, 19]])


### Indexing, Slicing, Joining, and Mutation
In this lesson, we will further explore how to manipulate tensors in PyTorch. The operations we will focus on are indexing, slicing, joining, and mutating tensors.

#### Indexing and Slicing
Like in Python and many other languages, indexing in PyTorch starts at 0. Let's create a 1-D tensor and access its elements:

In [10]:
import torch

t1 = torch.tensor([1, 2, 3, 4, 5])

# accessing the first element
print(t1[0])

# accessing the last element
print(t1[-1])

tensor(1)
tensor(5)


Slicing works similarly to Python's list slicing. You can select a range of elements in a tensor using the syntax [start:end]:

In [11]:
print(t1[1:3])  # prints elements at index 1 and 2

tensor([2, 3])


Indexing and slicing for multi-dimensional tensors work similarly, just with additional dimensions:

In [12]:
t2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# accessing a single element
print(t2[1, 2])  # prints element at row 1, column 2

# slicing
print(t2[1:, :2])  # prints all rows starting from 1, and columns up to 2

tensor(6)
tensor([[4, 5],
        [7, 8]])


#### Joining Tensors
You can join multiple tensors into one. The most common way to do this is by using torch.cat():

In [13]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])

# concatenating along the 0th dimension
t3 = torch.cat((t1, t2), dim=0)

print(t3)

tensor([1, 2, 3, 4, 5, 6])


You can also concatenate 2-D tensors along either dimension:

In [14]:
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])

t3 = torch.cat((t1, t2), dim=0)  # concatenating along rows
print(t3)

t4 = torch.cat((t1, t2), dim=1)  # concatenating along columns
print(t4)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


#### Mutation
Finally, let's look at how to modify a tensor. You can change an element of a tensor by accessing it and assigning a new value:

In [15]:
t1 = torch.tensor([1, 2, 3])

t1[1] = 7  # changing the second element

print(t1)

tensor([1, 7, 3])


You can also modify a slice of a tensor:

In [16]:
t1 = torch.tensor([1, 2, 3, 4, 5])

t1[1:4] = torch.tensor([7, 8, 9])  # changing elements at index 1, 2, and 3

print(t1)

tensor([1, 7, 8, 9, 5])


Remember that PyTorch tensors are mutable, meaning you can change their content without creating a new tensor.

### CUDA support, Moving computations to GPU
Deep learning models can be computationally intensive, and running them on a CPU can be slow. That's where Graphics Processing Units (GPUs) come in. GPUs are designed for performing large numbers of computations simultaneously, making them ideal for deep learning.
CUDA (Compute Unified Device Architecture) is a parallel computing platform and application programming interface (API) model created by Nvidia for general computing on its own GPUs. PyTorch has built-in support for CUDA, which allows it to seamlessly perform computations on a GPU, if one is available.

#### Checking for CUDA Availability
Before we can move computations to a GPU, we first need to check whether CUDA is available. We can do this using torch.cuda.is_available():

In [ ]:
import torch

print(torch.cuda.is_available())

This will output True if CUDA is available and False otherwise.

#### Moving Tensors to GPU
You can create a tensor on a GPU directly, or move a tensor from CPU to GPU.

To create a tensor on a GPU:

In [ ]:
t1 = torch.tensor([1, 2, 3], device='cuda')
print(t1)

Here, 'cuda:0' refers to the first GPU. If you have multiple GPUs and you want to create a tensor on the second GPU, you would use 'cuda:1', and so on.

To move a tensor from CPU to GPU:

In [ ]:
t2 = torch.tensor([4, 5, 6])
t2 = t2.to('cuda')

print(t2)

#### Performing Computations on GPU
Once a tensor is on a GPU, any operations performed on it are carried out on the GPU:

In [ ]:
t1 = torch.tensor([1, 2, 3], device='cuda')
t2 = torch.tensor([4, 5, 6], device='cuda')

t3 = t1 + t2  # this computation is performed on the GPU

print(t3)

Remember to ensure that all tensors involved in an operation are on the same device. If they're not, you'll need to move them first. Note that while using a GPU can greatly speed up computations, it also comes with its own challenges, such as managing GPU memory. However, these are stories for a more advanced tutorial.

### Automatic Differentiation with Autograd
When training neural networks, we often need to compute the gradients of loss functions with respect to the model's parameters, which are then used to update the parameters. This can be done using a technique called backpropagation.
Luckily, PyTorch provides a package called autograd for automatic differentiation, which simplifies the computation of backward passes. This is an essential tool for neural networks, and PyTorch makes it quite easy to use.

#### Tensors and Gradients
In PyTorch, you can tell an autograd-compatible tensor to remember its operations for backpropagation using .requires_grad_(True):

In [19]:
t1 = torch.tensor([1., 2., 3.], requires_grad=True)
print(t1)

tensor([1., 2., 3.], requires_grad=True)


This tensor t1 now has the ability to keep track of every operation involving it. Now, let's perform some operations:

In [20]:
t2 = t1 * 2
t3 = t2.mean()
print(t3)

tensor(4., grad_fn=<MeanBackward0>)


Here, t3 is created as a result of operations involving t1, so it has a grad_fn.
#### Backward Propagation
To perform backpropagation, we call .backward() on the tensor. This computes the gradient of t3 with respect to t1:

In [21]:
t3.backward()

After calling .backward(), the gradients are stored in the .grad attribute of the original tensor (t1):

In [22]:
print(t1.grad)

tensor([0.6667, 0.6667, 0.6667])


The gradient stored in t1.grad is the partial derivative of t3 with respect to t1. It's important to note that if t1's shape doesn't match with t3, PyTorch won't be able to directly compute the gradients. That's why when we are dealing with scalar loss in a neural network, we don't have to provide any arguments to backward(). Also, PyTorch accumulates the gradient in the .grad attribute, which means that it doesn't overwrite the previous values but instead adds the newly computed gradient. To clear the gradients for a new operation, you need to call .grad.zero_().

### PyTorch Libraries: Torchtext, torchvision, torchaudio
PyTorch is not just a deep learning library; it also has several companion libraries that provide additional functionality, such as handling specific types of data and performing various common operations. Today, we'll discuss three of these libraries: Torchtext, torchvision, and torchaudio.

#### Torchtext

Torchtext is a library for handling text data. It provides tools for creating datasets, handling tokenization, and managing vocabularies. It also includes several common datasets and pre-trained embeddings (like Word2Vec or GloVe). Here is a simple example of using Torchtext:

In [ ]:
from torchtext.data import Field, TabularDataset

# Define fields
TEXT = Field(sequential=True, tokenize='spacy', lower=True)
LABEL = Field(sequential=False, use_vocab=False)

# Define dataset
datafields = [("text", TEXT), ("label", LABEL)]
dataset = TabularDataset(path="mydata.csv", format='csv', fields=datafields)

# Build vocab
TEXT.build_vocab(dataset, vectors="glove.6B.100d")

# Now you can access the vocab using TEXT.vocab

#### Torchvision

Torchvision is a library for handling image data. It includes tools for transforming images, common image datasets (like CIFAR10, MNIST), and pre-trained models (like ResNet, VGG). Here is a simple example of using torchvision:

In [ ]:
from torchvision import datasets, transforms

# Define a transform
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Load a dataset
dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)

# torchvision also provides pre-trained models
from torchvision import models
model = models.resnet50(pretrained=True)

#### torchaudio

Torchaudio is a library for handling audio data. It provides tools for loading and saving audio data, transformations (like spectrograms, mel-scaling), and some common audio datasets. Here is a simple example of using torchaudio:

In [ ]:
!pip install torchaudio

In [1]:
import torchaudio

# Load an audio file
waveform, sample_rate = torchaudio.load('audio.wav')

# Apply a transform
transform = torchaudio.transforms.MFCC(sample_rate=sample_rate)
mfcc = transform(waveform)

# torchaudio also includes some common datasets
yesno_data = torchaudio.datasets.YESNO('.', download=True)

ModuleNotFoundError: No module named 'torchaudio'